In [1]:
%matplotlib inline

In [2]:
import matplotlib
import matplotlib as plt
import numpy as np

print(matplotlib.__version__)
print(np.__version__)

3.4.3
1.20.3


In [3]:
np.random.seed(2)
data=np.random.normal(loc=100,scale=10,size=200)
data

array([ 95.83242153,  99.43733173,  78.63803904, 116.40270808,
        82.06564415,  91.58252634, 105.02881417,  87.54711913,
        89.42047781,  90.90992385, 105.51454045, 122.92208013,
       100.41539393,  88.82074555, 105.39058321,  94.038403  ,
        99.80869503, 111.7500122 ,  92.52129051, 100.09025251,
        91.21892107,  98.4356583 , 102.56570452,  90.11220951,
        96.61178034,  97.63815969,  93.62344988,  88.12387714,
        85.78782773,  98.46504804,  97.3094304 , 122.31366789,
        75.65232423, 101.12726505, 103.70444537, 113.59633863,
       105.01857207,  91.55786296, 100.00009761, 105.42352572,
        96.86491803, 107.71011738,  81.31909345, 117.31184666,
       114.67678011,  96.64322661, 106.1134078 , 100.47970592,
        91.70864711, 100.87710218, 110.00365887,  96.18907482,
        96.24330577,  99.25529237, 104.3349633 , 112.7837923 ,
        93.65320695, 105.08396243, 102.16116006,  81.41387614,
        95.80683518,  98.67671102,  99.6042976 , 103.26

In [6]:
plt.boxplot(data, labels=['Data'])

plt.title('Simple Box Plot')
plt.xlabel('sumbu X')
plt.ylabel('sumbu Y')
plt.grid()
plt.show()

AttributeError: module 'matplotlib' has no attribute 'boxplot'

In [7]:
plt.boxplot(data, labels=['Data'],notch=True)

plt.title('Notched Box Plot')
plt.xlabel('sumbu X')
plt.ylabel('sumbu Y')

plt.show()

AttributeError: module 'matplotlib' has no attribute 'boxplot'

In [9]:
plt.boxplot(data,
            labels=['Data'],
            showfliers=True,
            flierprops={'markerfacecolor':'r', 'marker':'d'})

plt.title('pengaturan Marker')
plt.xlabel('sumbu X')
plt.ylabel('sumbu Y')

plt.show()

AttributeError: module 'matplotlib' has no attribute 'boxplot'

In [10]:
plt.boxplot(data, labels=['Data'],vert=False)

plt.title('Horisontal Box Plot')
plt.xlabel('sumbu X')
plt.ylabel('sumbu Y')

plt.show()

AttributeError: module 'matplotlib' has no attribute 'boxplot'

In [14]:
np.random.seed(10)
data1=np.random.normal(100,10,200)
data2=np.random.normal(80,30,200)
data3=np.random.normal(70,20,200)
data4=np.random.normal(70,25,200)

data=[data1,data2,data3,data4]
labels=['data 1','data 2','data 3','data 4']

In [15]:
plt.boxplot(data,lebels=lebels)

plt.title('multiple Box Plot')
plt.xlabel('sumbu X')
plt.ylabel('sumbu Y')

plt.show()

AttributeError: module 'matplotlib' has no attribute 'boxplot'

In [16]:
np.random.seed(2)
data=np.random.normal(loc=100,scale=10,size=200)
data

array([ 95.83242153,  99.43733173,  78.63803904, 116.40270808,
        82.06564415,  91.58252634, 105.02881417,  87.54711913,
        89.42047781,  90.90992385, 105.51454045, 122.92208013,
       100.41539393,  88.82074555, 105.39058321,  94.038403  ,
        99.80869503, 111.7500122 ,  92.52129051, 100.09025251,
        91.21892107,  98.4356583 , 102.56570452,  90.11220951,
        96.61178034,  97.63815969,  93.62344988,  88.12387714,
        85.78782773,  98.46504804,  97.3094304 , 122.31366789,
        75.65232423, 101.12726505, 103.70444537, 113.59633863,
       105.01857207,  91.55786296, 100.00009761, 105.42352572,
        96.86491803, 107.71011738,  81.31909345, 117.31184666,
       114.67678011,  96.64322661, 106.1134078 , 100.47970592,
        91.70864711, 100.87710218, 110.00365887,  96.18907482,
        96.24330577,  99.25529237, 104.3349633 , 112.7837923 ,
        93.65320695, 105.08396243, 102.16116006,  81.41387614,
        95.80683518,  98.67671102,  99.6042976 , 103.26

In [17]:
plt.violinplot(data)

plt.title('Simple Violin Plot')
plt.xlabel('sumbu X')
plt.ylabel('sumbu Y')

plt.show()

AttributeError: module 'matplotlib' has no attribute 'violinplot'

In [18]:
plt.violinplot(data,
               showextrema=False,
               showmeans=False,
               showmedian=False,
               quantitles=None)

plt.title('Violin Plot')
plt.xlabel('Sumbu X')
plt.ylabel('Sumbu Y')

plt.show()

AttributeError: module 'matplotlib' has no attribute 'violinplot'

In [19]:
plt.violinplot(data,vert=False)

plt.title('Horisotal Violin Plot')
plt.xlabel('sumbu X')
plt.ylabel('sumbu Y')

plt.show()

AttributeError: module 'matplotlib' has no attribute 'violinplot'

In [20]:
np.random.seed(10)
data1=np.random.normal(100,10,200)
data2=np.random.normal(80,30,200)
data3=np.random.normal(70,20,200)
data4=np.random.normal(70,25,200)

data=[data1,data2,data3,data4]
labels=['data 1','data 2','data 3','data 4']

In [21]:
plt.violinplot(data)

plt.title('Multiple Violin Plot')
plt.xlabel('sumbu X')
plt.ylabel('sumbu Y')

plt.show()

AttributeError: module 'matplotlib' has no attribute 'violinplot'

In [23]:
x= np.linspace(1,10,25)
x

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [24]:
fig,ax1 = plt.subplots()

ax1.plot(x,np.exp(x),'bs-',label='exp')
ax1.set_xlabel('sumbu X')
ax1.set_ylabel('exp')

ax2=ax1.twinx()
ax2.plot(x,np.log(x),'ro-',label='log')
ax2.set_ylabel('log')

fig.suptitle('Contoh Twin Axes')
fig.legend(loc='upper left')

plt.show()

AttributeError: module 'matplotlib' has no attribute 'subplots'

In [25]:
x=np.random.randint(16,40,size=30)
x

array([23, 22, 22, 23, 37, 27, 33, 29, 31, 25, 36, 18, 22, 21, 30, 38, 30,
       18, 35, 39, 25, 38, 30, 26, 21, 23, 20, 23, 27, 25])

In [26]:
def C2F(celsius=0):
    return(celsius*1.8)+32
def konversi_sumbu(ax1):
    y1,y2=ax1.get_ylim()
    ax2.set_ylim(C2F(y1),C2F(y2))
    ax2.figure.canvas.draw()
   
fig, ax1=plt.subplots()
ax2=ax1.twinx()

ax1.callbacks.connect('ylim_changed',konvers_sumbu)
ax1.plot(x)

ax1.set_xlabel('Hari')
ax1.set_ylabel('celsius')
ax2.set_ylabel('Fahrenheit')

fig.suptitle('Temperatur Udara')
plr.show()

AttributeError: module 'matplotlib' has no attribute 'subplots'